FROM node:12.18.1-alpine

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install --only-production
COPY ./src ./src

# ENV DBHOST "mongodb://db:27017"
# ENV DBNAME "videos"

CMD npx wait-port rabbit:5672 && \
npm start