version: '3'
services:
  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: "always"
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: "always"
  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - ../tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
      - ./video-streaming/videos:/usr/src/app/video:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on:
      - rabbit
    restart: "no"
  
  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - ../tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on:
      - db
      - rabbit
    restart: "no"
  recommendations:
    image: recommendations
    build: 
      context: ./recommendations
      dockerfile: Dockerfile-dev
    volumes:
      - ../tmp/recommendations/npm-cache:/root/.npm:z
      - ./recommendations/src:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=recommendations
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"


